### ISSUE TITLE
SPM12 Does Not Work With PVElab Atlas Step

### ISSUE THREAD

**Issue by Ianyliu** [swederik/pvelab#1]
https://github.com/swederik/pvelab/blob/8380a0d0729688992b58a0ede152967bd0d04bc2/IBB_wrapper/Atlas2_wrapper.m#L138
In this line (and the following lines) of code, only SPM versions 2, 5, and 8 are allowed, but not 12.... is there a reason for this?

**Comment by Ianyliu** [comment]
Also, it seems that SPM12 does not have an `apriori` directory, which is required for PVE correction? 

Is there a way for me to use PVE correction without reinstalling SPM8?

**Comment by ChristophePhillips** [comment]
Well, those bits of code date from around 2014, and the first full release of SPM12 dates from October 2014, see the [announcement email](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=SPM;df449c35.1410) and list of [tagged versions](https://github.com/spm/spm12/tags) (from the old SVN server). So my best guess is that SPM12 was not there yet or widely used when the code was released, then no one updated it afterwards...

And indeed, there is no `apriori` folder in SPM12. The tissue prior maps are all bundled into the `TPM.nii` file in the `tpm` folder.

So to use this code with SPM12, you'd need to update the code in at least 2 places
- when checking the version, make sure it likes SPM12;
- when looks for priors, make sure it used the right frame in the `TPM.nii` file. Or you can add the `apriori` folder from SPM8 into SPM12.

Best.

**Comment by Ianyliu** [comment]
Got it, thank you so much @ChristophePhillips
